version: '3.0'
services:
  rasa:
    container_name: "rasa_server"
    build:
      context: .
    volumes:
      - ./:/app
    ports:
    - 5005:5005
    command: ["run","-m","/app/models","--enable-api","--cors","*","--debug" ]


  action-server:
    container_name: "action_server"
    build:
      context: actions
    volumes:
    - ./actions:/app/actions
    ports:
    - "5055:5055"

  # rasa_x-server:
  #   image: rasa/rasa-x:latest
  #   ports:
  #   - "5002:5002"
  #   command: rasa x


